---
title: "KRR on vowel harmony"
output: html_document
date: "2026-04-13"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# -- head -- #

setwd('~/Github/Racz2027vh/')
library(tidyverse)
library(krr)

# -- fun -- #

transcribeIPA = function(dat){dat |> stringr::str_replace_all(c('x' = 'ks', 'cs' = 'č', 'zs' = 'ž', 'ty' = 'ṯ', 'gy' = 'ḏ', 'ny' = 'ṉ', 'sz' = 'ß', 's' = 'š', 'ß' = 's', 'ck' = 'kk', 'codec' = 'kodek', 'ch' = 'h', 'ly' = 'j'))}

# -- read -- #

train = read_tsv('dat/dzsungel.tsv')
test_non = read_tsv('dat/filtered_data_nonword.tsv')
test_real = read_tsv('dat/filtered_data_real_word.tsv')

# counts
length(unique(test_non$id))
length(unique(test_real$id))

```

## running janet (done)

```{r janet, eval = F}

library(janet)

# Read your phonological feature matrix (segment col + binary feature cols)
features <- read.delim("dat/siptar_torkenczy_toth_racz_hungarian.tsv", na.strings = "")

# Supply a character vector of words
# words <- readLines("words.txt")
raw = c(unique(test_non$target),unique(train$stem))
words = transcribeIPA(raw)

# Run the full pipeline
result <- run_janet(features, words, gap_penalty = 1.0)

# look at all this fancy information stored in result
result

write_tsv(result$word_distances, 'dat/word_distances.tsv.gz')
```

## reading in dist

```{r dist}

dist = read_tsv('dat/word_distances.tsv.gz')

```

Training data from [here](https://github.com/petyaracz/RaczRebrus2024) (see [here](https://www.degruyterbrill.com/document/doi/10.1515/cllt-2024-0021)). Nonword test data from [here](https://github.com/petyaracz/Racz2024) (see [here](https://onlinelibrary.wiley.com/doi/full/10.1111/cogs.13483)). Real word test data from [here])(https://github.com/petyaracz/RaczRebrus2024cont) (rn unpublished).

```{r wiggle}

train = train |> 
  mutate(
    transcribed = transcribeIPA(stem)
  )

test_real = test_real |> 
  mutate(
    transcribed = transcribeIPA(stem)
  )

test_non = test_non |> 
  mutate(
    transcribed = transcribeIPA(target)
  )

test_real2 = test_real |> 
  count(transcribed,accept) |> 
  pivot_wider(names_from = accept, values_from = n, values_fill = 0) |> 
  mutate(
    log_odds_back = log((`TRUE`+0.001)/(`FALSE`+0.001))
      )

test_non2 = test_non |>
  count(transcribed,accept) |> 
  pivot_wider(names_from = accept, values_from = n, values_fill = 0) |> 
  mutate(
    log_odds_back = log((`TRUE`+0.001)/(`FALSE`+0.001))
      )

```

## model training

```{r model_training}

check_krr_inputs(train = train, dist = dist, word_col = 'transcribed', outcome_col = 'p_back')

# -- model -- #

# Train KRR with LOO hyperparameter tuning on corpus data.
# link = "logit" transforms probabilities to log-odds before fitting and
# back-transforms predictions; criterion = "rmse" selects the (sigma, alpha)
# pair with the lowest LOO root-mean-squared error in the transformed space.
m = train_krr(train, dist, word_col = "transcribed", outcome_col = "log_odds_back", link = "identity", criterion = 'rmse')
m$sigma   # best sigma
m$alpha   # best alpha
m$best_score # logit: 2.28 # identity: 2.39

train2 = m$predictions

```

## real words

```{r model_test_real}
# existing words. this is just a look-up
test_real3 = inner_join(train2,test_real2)

```

```{r check_test_real}

test_real3 |> 
  ggplot(aes(predicted_loo,observed)) +
  geom_point()

test_real3 |> 
  ggplot(aes(observed,log_odds_back)) +
  geom_point()

test_real3 |> 
  ggplot(aes(predicted_loo,log_odds_back)) +
  geom_point()

with(test_real3, cor.test(predicted_loo,log_odds_back))
with(test_real3, cor.test(predicted_loo,observed))

```

# nonwords

```{r model_test_non}

preds = predict_krr(train_data = train, test_data = test_non2, dist_df = dist, word_col = "transcribed", outcome_col = "log_odds_back",
                     sigma = m$sigma, alpha = m$alpha, link = "identity")
```

```{r check_test_non}

preds |> 
  ggplot(aes(predicted,observed)) +
  geom_point()

with(preds, cor.test(predicted,observed))

```

```{r setup_properly}

test_real_min = test_real3 |> 
  select(transcribed,predicted_loo)

test_non_min = preds |> 
  select(transcribed,predicted)

test_real4 = test_real |> 
  left_join(test_real_min) |> 
  mutate(
    pred = predicted_loo,
    type = 'real'
  ) |> 
  select(accept,id,transcribed,pred,type)

test_non4 = test_non |> 
  left_join(test_non_min) |> 
  mutate(
    pred = predicted,
    type = 'nonword'
  ) |> 
  select(accept,id,transcribed,pred,type)

tests = bind_rows(test_real4,test_non4) |> 
  mutate(accept = as.double(accept)) |> 
  filter(!is.na(accept),!is.na(pred)) # ahem

```

```{r model_properly}
library(glmmTMB)
library(broom.mixed)
library(performance)
library(sjPlot)
library(emmeans)

fit1 = glmmTMB(
  accept ~ pred * type + (1|id) + (1|transcribed),
  family = binomial,
  data = tests
)

fit2 = glmmTMB(
  accept ~ pred * type + (1+pred|id) + (1|transcribed),
  family = binomial,
  data = tests
)

compare_performance(fit1,fit2,metrics = 'common')
summary(fit2)
tidy(fit2)
check_model(fit2)
plot_model(fit2, 'pred', terms = c('pred', 'type'))

emmeans(fit2, ~ type, type = "response", level = .95)
r2(fit2)

# Get contribution of pred only (marginal over random effects)
tests$fitted_pred_only = predict(fit2, re.form = NA, type = "response")

tests |> 
  group_by(type) |> 
  summarise(
    r2_pred_marginal = cor(fitted_pred_only, accept)^2,
    n = n()
  )

# a lot of variation is eaten by the random effects, which is entirely a hell of my own making
```
