stim = [
  {
    "class": "művelt",
    "ending": "en",
    "s0": "Ez egy szláken.",
    "name": "s1",
    "value": "Azok ott szlákenok.",
    "target": "szláken",
    "trial_type": "dat",
    "prompt": "<p>Ez egy szláken. Azok ott szlákenok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">szláken<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "en",
    "s0": "Ez egy szláken.",
    "name": "s2",
    "value": "Elneveztem a kutyámat szlákennak.",
    "target": "szláken",
    "trial_type": "dat",
    "prompt": "<p>Ez egy szláken. Elneveztem a kutyámat szlákennak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">szláken<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "en",
    "s0": "Ez egy daken.",
    "name": "s1",
    "value": "Azok ott dakenok.",
    "target": "daken",
    "trial_type": "dat",
    "prompt": "<p>Ez egy daken. Azok ott dakenok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">daken<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "en",
    "s0": "Ez egy daken.",
    "name": "s2",
    "value": "Elneveztem a kutyámat dakennak.",
    "target": "daken",
    "trial_type": "dat",
    "prompt": "<p>Ez egy daken. Elneveztem a kutyámat dakennak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">daken<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "en",
    "s0": "Ez egy bálen.",
    "name": "s1",
    "value": "Azok ott bálenok.",
    "target": "bálen",
    "trial_type": "dat",
    "prompt": "<p>Ez egy bálen. Azok ott bálenok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bálen<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "en",
    "s0": "Ez egy bálen.",
    "name": "s2",
    "value": "Elneveztem a kutyámat bálennak.",
    "target": "bálen",
    "trial_type": "dat",
    "prompt": "<p>Ez egy bálen. Elneveztem a kutyámat bálennak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bálen<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "en",
    "s0": "Ez egy laben.",
    "name": "s1",
    "value": "Azok ott labenok.",
    "target": "laben",
    "trial_type": "dat",
    "prompt": "<p>Ez egy laben. Azok ott labenok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">laben<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "en",
    "s0": "Ez egy laben.",
    "name": "s2",
    "value": "Elneveztem a kutyámat labennak.",
    "target": "laben",
    "trial_type": "dat",
    "prompt": "<p>Ez egy laben. Elneveztem a kutyámat labennak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">laben<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "en",
    "s0": "Ez egy pámen.",
    "name": "s1",
    "value": "Azok ott pámenok.",
    "target": "pámen",
    "trial_type": "dat",
    "prompt": "<p>Ez egy pámen. Azok ott pámenok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">pámen<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "en",
    "s0": "Ez egy pámen.",
    "name": "s2",
    "value": "Elneveztem a kutyámat pámennak.",
    "target": "pámen",
    "trial_type": "dat",
    "prompt": "<p>Ez egy pámen. Elneveztem a kutyámat pámennak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">pámen<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ett",
    "s0": "Ez egy vódett.",
    "name": "s1",
    "value": "Azok ott vódettok.",
    "target": "vódett",
    "trial_type": "dat",
    "prompt": "<p>Ez egy vódett. Azok ott vódettok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">vódett<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ett",
    "s0": "Ez egy vódett.",
    "name": "s2",
    "value": "Elneveztem a kutyámat vódettnak.",
    "target": "vódett",
    "trial_type": "dat",
    "prompt": "<p>Ez egy vódett. Elneveztem a kutyámat vódettnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">vódett<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ett",
    "s0": "Ez egy rojett.",
    "name": "s1",
    "value": "Azok ott rojettok.",
    "target": "rojett",
    "trial_type": "dat",
    "prompt": "<p>Ez egy rojett. Azok ott rojettok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">rojett<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ett",
    "s0": "Ez egy rojett.",
    "name": "s2",
    "value": "Elneveztem a kutyámat rojettnak.",
    "target": "rojett",
    "trial_type": "dat",
    "prompt": "<p>Ez egy rojett. Elneveztem a kutyámat rojettnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">rojett<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ett",
    "s0": "Ez egy bondett.",
    "name": "s1",
    "value": "Azok ott bondettok.",
    "target": "bondett",
    "trial_type": "dat",
    "prompt": "<p>Ez egy bondett. Azok ott bondettok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bondett<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ett",
    "s0": "Ez egy bondett.",
    "name": "s2",
    "value": "Elneveztem a kutyámat bondettnak.",
    "target": "bondett",
    "trial_type": "dat",
    "prompt": "<p>Ez egy bondett. Elneveztem a kutyámat bondettnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bondett<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ett",
    "s0": "Ez egy pofszett.",
    "name": "s1",
    "value": "Azok ott pofszettok.",
    "target": "pofszett",
    "trial_type": "dat",
    "prompt": "<p>Ez egy pofszett. Azok ott pofszettok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">pofszett<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ett",
    "s0": "Ez egy pofszett.",
    "name": "s2",
    "value": "Elneveztem a kutyámat pofszettnak.",
    "target": "pofszett",
    "trial_type": "dat",
    "prompt": "<p>Ez egy pofszett. Elneveztem a kutyámat pofszettnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">pofszett<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ett",
    "s0": "Ez egy ojett.",
    "name": "s1",
    "value": "Azok ott ojettok.",
    "target": "ojett",
    "trial_type": "dat",
    "prompt": "<p>Ez egy ojett. Azok ott ojettok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">ojett<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ett",
    "s0": "Ez egy ojett.",
    "name": "s2",
    "value": "Elneveztem a kutyámat ojettnak.",
    "target": "ojett",
    "trial_type": "dat",
    "prompt": "<p>Ez egy ojett. Elneveztem a kutyámat ojettnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">ojett<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ens",
    "s0": "Ez egy slotens.",
    "name": "s1",
    "value": "Azok ott slotensok.",
    "target": "slotens",
    "trial_type": "dat",
    "prompt": "<p>Ez egy slotens. Azok ott slotensok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">slotens<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ens",
    "s0": "Ez egy slotens.",
    "name": "s2",
    "value": "Elneveztem a kutyámat slotensnak.",
    "target": "slotens",
    "trial_type": "dat",
    "prompt": "<p>Ez egy slotens. Elneveztem a kutyámat slotensnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">slotens<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ens",
    "s0": "Ez egy hókens.",
    "name": "s1",
    "value": "Azok ott hókensok.",
    "target": "hókens",
    "trial_type": "dat",
    "prompt": "<p>Ez egy hókens. Azok ott hókensok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">hókens<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ens",
    "s0": "Ez egy hókens.",
    "name": "s2",
    "value": "Elneveztem a kutyámat hókensnak.",
    "target": "hókens",
    "trial_type": "dat",
    "prompt": "<p>Ez egy hókens. Elneveztem a kutyámat hókensnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">hókens<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ens",
    "s0": "Ez egy pódens.",
    "name": "s1",
    "value": "Azok ott pódensok.",
    "target": "pódens",
    "trial_type": "dat",
    "prompt": "<p>Ez egy pódens. Azok ott pódensok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">pódens<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ens",
    "s0": "Ez egy pódens.",
    "name": "s2",
    "value": "Elneveztem a kutyámat pódensnak.",
    "target": "pódens",
    "trial_type": "dat",
    "prompt": "<p>Ez egy pódens. Elneveztem a kutyámat pódensnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">pódens<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ens",
    "s0": "Ez egy voglens.",
    "name": "s1",
    "value": "Azok ott voglensok.",
    "target": "voglens",
    "trial_type": "dat",
    "prompt": "<p>Ez egy voglens. Azok ott voglensok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">voglens<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ens",
    "s0": "Ez egy voglens.",
    "name": "s2",
    "value": "Elneveztem a kutyámat voglensnak.",
    "target": "voglens",
    "trial_type": "dat",
    "prompt": "<p>Ez egy voglens. Elneveztem a kutyámat voglensnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">voglens<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ens",
    "s0": "Ez egy loftvens.",
    "name": "s1",
    "value": "Azok ott loftvensok.",
    "target": "loftvens",
    "trial_type": "dat",
    "prompt": "<p>Ez egy loftvens. Azok ott loftvensok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">loftvens<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ens",
    "s0": "Ez egy loftvens.",
    "name": "s2",
    "value": "Elneveztem a kutyámat loftvensnak.",
    "target": "loftvens",
    "trial_type": "dat",
    "prompt": "<p>Ez egy loftvens. Elneveztem a kutyámat loftvensnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">loftvens<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ex",
    "s0": "Ez egy dubex.",
    "name": "s1",
    "value": "Azok ott dubexok.",
    "target": "dubex",
    "trial_type": "dat",
    "prompt": "<p>Ez egy dubex. Azok ott dubexok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">dubex<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ex",
    "s0": "Ez egy dubex.",
    "name": "s2",
    "value": "Elneveztem a kutyámat dubexnak.",
    "target": "dubex",
    "trial_type": "dat",
    "prompt": "<p>Ez egy dubex. Elneveztem a kutyámat dubexnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">dubex<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ex",
    "s0": "Ez egy kojex.",
    "name": "s1",
    "value": "Azok ott kojexok.",
    "target": "kojex",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kojex. Azok ott kojexok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kojex<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ex",
    "s0": "Ez egy kojex.",
    "name": "s2",
    "value": "Elneveztem a kutyámat kojexnak.",
    "target": "kojex",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kojex. Elneveztem a kutyámat kojexnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kojex<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ex",
    "s0": "Ez egy tokex.",
    "name": "s1",
    "value": "Azok ott tokexok.",
    "target": "tokex",
    "trial_type": "dat",
    "prompt": "<p>Ez egy tokex. Azok ott tokexok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">tokex<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ex",
    "s0": "Ez egy tokex.",
    "name": "s2",
    "value": "Elneveztem a kutyámat tokexnak.",
    "target": "tokex",
    "trial_type": "dat",
    "prompt": "<p>Ez egy tokex. Elneveztem a kutyámat tokexnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">tokex<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ex",
    "s0": "Ez egy bojex.",
    "name": "s1",
    "value": "Azok ott bojexok.",
    "target": "bojex",
    "trial_type": "dat",
    "prompt": "<p>Ez egy bojex. Azok ott bojexok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bojex<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ex",
    "s0": "Ez egy bojex.",
    "name": "s2",
    "value": "Elneveztem a kutyámat bojexnak.",
    "target": "bojex",
    "trial_type": "dat",
    "prompt": "<p>Ez egy bojex. Elneveztem a kutyámat bojexnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bojex<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ex",
    "s0": "Ez egy trumlex.",
    "name": "s1",
    "value": "Azok ott trumlexok.",
    "target": "trumlex",
    "trial_type": "dat",
    "prompt": "<p>Ez egy trumlex. Azok ott trumlexok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">trumlex<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "ex",
    "s0": "Ez egy trumlex.",
    "name": "s2",
    "value": "Elneveztem a kutyámat trumlexnak.",
    "target": "trumlex",
    "trial_type": "dat",
    "prompt": "<p>Ez egy trumlex. Elneveztem a kutyámat trumlexnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">trumlex<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "em",
    "s0": "Ez egy mojem.",
    "name": "s1",
    "value": "Azok ott mojemok.",
    "target": "mojem",
    "trial_type": "dat",
    "prompt": "<p>Ez egy mojem. Azok ott mojemok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">mojem<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "em",
    "s0": "Ez egy mojem.",
    "name": "s2",
    "value": "Elneveztem a kutyámat mojemnak.",
    "target": "mojem",
    "trial_type": "dat",
    "prompt": "<p>Ez egy mojem. Elneveztem a kutyámat mojemnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">mojem<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "em",
    "s0": "Ez egy ubrem.",
    "name": "s1",
    "value": "Azok ott ubremok.",
    "target": "ubrem",
    "trial_type": "dat",
    "prompt": "<p>Ez egy ubrem. Azok ott ubremok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">ubrem<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "em",
    "s0": "Ez egy ubrem.",
    "name": "s2",
    "value": "Elneveztem a kutyámat ubremnak.",
    "target": "ubrem",
    "trial_type": "dat",
    "prompt": "<p>Ez egy ubrem. Elneveztem a kutyámat ubremnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">ubrem<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "em",
    "s0": "Ez egy tosztem.",
    "name": "s1",
    "value": "Azok ott tosztemok.",
    "target": "tosztem",
    "trial_type": "dat",
    "prompt": "<p>Ez egy tosztem. Azok ott tosztemok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">tosztem<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "em",
    "s0": "Ez egy tosztem.",
    "name": "s2",
    "value": "Elneveztem a kutyámat tosztemnak.",
    "target": "tosztem",
    "trial_type": "dat",
    "prompt": "<p>Ez egy tosztem. Elneveztem a kutyámat tosztemnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">tosztem<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "em",
    "s0": "Ez egy próngem.",
    "name": "s1",
    "value": "Azok ott próngemok.",
    "target": "próngem",
    "trial_type": "dat",
    "prompt": "<p>Ez egy próngem. Azok ott próngemok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">próngem<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "em",
    "s0": "Ez egy próngem.",
    "name": "s2",
    "value": "Elneveztem a kutyámat próngemnak.",
    "target": "próngem",
    "trial_type": "dat",
    "prompt": "<p>Ez egy próngem. Elneveztem a kutyámat próngemnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">próngem<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "em",
    "s0": "Ez egy plosztem.",
    "name": "s1",
    "value": "Azok ott plosztemok.",
    "target": "plosztem",
    "trial_type": "dat",
    "prompt": "<p>Ez egy plosztem. Azok ott plosztemok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">plosztem<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "művelt",
    "ending": "em",
    "s0": "Ez egy plosztem.",
    "name": "s2",
    "value": "Elneveztem a kutyámat plosztemnak.",
    "target": "plosztem",
    "trial_type": "dat",
    "prompt": "<p>Ez egy plosztem. Elneveztem a kutyámat plosztemnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">plosztem<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "er",
    "s0": "Ez egy bórcer.",
    "name": "s1",
    "value": "Azok ott bórcerok.",
    "target": "bórcer",
    "trial_type": "dat",
    "prompt": "<p>Ez egy bórcer. Azok ott bórcerok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bórcer<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "er",
    "s0": "Ez egy bórcer.",
    "name": "s2",
    "value": "Elneveztem a kutyámat bórcernak.",
    "target": "bórcer",
    "trial_type": "dat",
    "prompt": "<p>Ez egy bórcer. Elneveztem a kutyámat bórcernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bórcer<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "er",
    "s0": "Ez egy suter.",
    "name": "s1",
    "value": "Azok ott suterok.",
    "target": "suter",
    "trial_type": "dat",
    "prompt": "<p>Ez egy suter. Azok ott suterok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">suter<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "er",
    "s0": "Ez egy suter.",
    "name": "s2",
    "value": "Elneveztem a kutyámat suternak.",
    "target": "suter",
    "trial_type": "dat",
    "prompt": "<p>Ez egy suter. Elneveztem a kutyámat suternak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">suter<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "er",
    "s0": "Ez egy stokler.",
    "name": "s1",
    "value": "Azok ott stoklerok.",
    "target": "stokler",
    "trial_type": "dat",
    "prompt": "<p>Ez egy stokler. Azok ott stoklerok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">stokler<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "er",
    "s0": "Ez egy stokler.",
    "name": "s2",
    "value": "Elneveztem a kutyámat stoklernak.",
    "target": "stokler",
    "trial_type": "dat",
    "prompt": "<p>Ez egy stokler. Elneveztem a kutyámat stoklernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">stokler<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "er",
    "s0": "Ez egy kajler.",
    "name": "s1",
    "value": "Azok ott kajlerok.",
    "target": "kajler",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kajler. Azok ott kajlerok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kajler<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "er",
    "s0": "Ez egy kajler.",
    "name": "s2",
    "value": "Elneveztem a kutyámat kajlernak.",
    "target": "kajler",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kajler. Elneveztem a kutyámat kajlernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kajler<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "er",
    "s0": "Ez egy kokker.",
    "name": "s1",
    "value": "Azok ott kokkerok.",
    "target": "kokker",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kokker. Azok ott kokkerok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kokker<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "er",
    "s0": "Ez egy kokker.",
    "name": "s2",
    "value": "Elneveztem a kutyámat kokkernak.",
    "target": "kokker",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kokker. Elneveztem a kutyámat kokkernak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kokker<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "esz",
    "s0": "Ez egy kamesz.",
    "name": "s1",
    "value": "Azok ott kameszok.",
    "target": "kamesz",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kamesz. Azok ott kameszok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kamesz<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "esz",
    "s0": "Ez egy kamesz.",
    "name": "s2",
    "value": "Elneveztem a kutyámat kamesznak.",
    "target": "kamesz",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kamesz. Elneveztem a kutyámat kamesznak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kamesz<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "esz",
    "s0": "Ez egy bachesz.",
    "name": "s1",
    "value": "Azok ott bacheszok.",
    "target": "bachesz",
    "trial_type": "dat",
    "prompt": "<p>Ez egy bachesz. Azok ott bacheszok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bachesz<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "esz",
    "s0": "Ez egy bachesz.",
    "name": "s2",
    "value": "Elneveztem a kutyámat bachesznak.",
    "target": "bachesz",
    "trial_type": "dat",
    "prompt": "<p>Ez egy bachesz. Elneveztem a kutyámat bachesznak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bachesz<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "esz",
    "s0": "Ez egy takkesz.",
    "name": "s1",
    "value": "Azok ott takkeszok.",
    "target": "takkesz",
    "trial_type": "dat",
    "prompt": "<p>Ez egy takkesz. Azok ott takkeszok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">takkesz<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "esz",
    "s0": "Ez egy takkesz.",
    "name": "s2",
    "value": "Elneveztem a kutyámat takkesznak.",
    "target": "takkesz",
    "trial_type": "dat",
    "prompt": "<p>Ez egy takkesz. Elneveztem a kutyámat takkesznak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">takkesz<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "esz",
    "s0": "Ez egy kampesz.",
    "name": "s1",
    "value": "Azok ott kampeszok.",
    "target": "kampesz",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kampesz. Azok ott kampeszok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kampesz<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "esz",
    "s0": "Ez egy kampesz.",
    "name": "s2",
    "value": "Elneveztem a kutyámat kampesznak.",
    "target": "kampesz",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kampesz. Elneveztem a kutyámat kampesznak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kampesz<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "esz",
    "s0": "Ez egy gortesz.",
    "name": "s1",
    "value": "Azok ott gorteszok.",
    "target": "gortesz",
    "trial_type": "dat",
    "prompt": "<p>Ez egy gortesz. Azok ott gorteszok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">gortesz<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "esz",
    "s0": "Ez egy gortesz.",
    "name": "s2",
    "value": "Elneveztem a kutyámat gortesznak.",
    "target": "gortesz",
    "trial_type": "dat",
    "prompt": "<p>Ez egy gortesz. Elneveztem a kutyámat gortesznak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">gortesz<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ek",
    "s0": "Ez egy flotek.",
    "name": "s1",
    "value": "Azok ott flotekok.",
    "target": "flotek",
    "trial_type": "dat",
    "prompt": "<p>Ez egy flotek. Azok ott flotekok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">flotek<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ek",
    "s0": "Ez egy flotek.",
    "name": "s2",
    "value": "Elneveztem a kutyámat floteknak.",
    "target": "flotek",
    "trial_type": "dat",
    "prompt": "<p>Ez egy flotek. Elneveztem a kutyámat floteknak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">flotek<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ek",
    "s0": "Ez egy bralek.",
    "name": "s1",
    "value": "Azok ott bralekok.",
    "target": "bralek",
    "trial_type": "dat",
    "prompt": "<p>Ez egy bralek. Azok ott bralekok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bralek<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ek",
    "s0": "Ez egy bralek.",
    "name": "s2",
    "value": "Elneveztem a kutyámat braleknak.",
    "target": "bralek",
    "trial_type": "dat",
    "prompt": "<p>Ez egy bralek. Elneveztem a kutyámat braleknak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">bralek<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ek",
    "s0": "Ez egy saklek.",
    "name": "s1",
    "value": "Azok ott saklekok.",
    "target": "saklek",
    "trial_type": "dat",
    "prompt": "<p>Ez egy saklek. Azok ott saklekok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">saklek<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ek",
    "s0": "Ez egy saklek.",
    "name": "s2",
    "value": "Elneveztem a kutyámat sakleknak.",
    "target": "saklek",
    "trial_type": "dat",
    "prompt": "<p>Ez egy saklek. Elneveztem a kutyámat sakleknak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">saklek<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ek",
    "s0": "Ez egy kumek.",
    "name": "s1",
    "value": "Azok ott kumekok.",
    "target": "kumek",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kumek. Azok ott kumekok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kumek<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ek",
    "s0": "Ez egy kumek.",
    "name": "s2",
    "value": "Elneveztem a kutyámat kumeknak.",
    "target": "kumek",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kumek. Elneveztem a kutyámat kumeknak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kumek<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ek",
    "s0": "Ez egy kacsek.",
    "name": "s1",
    "value": "Azok ott kacsekok.",
    "target": "kacsek",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kacsek. Azok ott kacsekok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kacsek<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ek",
    "s0": "Ez egy kacsek.",
    "name": "s2",
    "value": "Elneveztem a kutyámat kacseknak.",
    "target": "kacsek",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kacsek. Elneveztem a kutyámat kacseknak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kacsek<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ec",
    "s0": "Ez egy baktec.",
    "name": "s1",
    "value": "Azok ott baktecok.",
    "target": "baktec",
    "trial_type": "dat",
    "prompt": "<p>Ez egy baktec. Azok ott baktecok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">baktec<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ec",
    "s0": "Ez egy baktec.",
    "name": "s2",
    "value": "Elneveztem a kutyámat baktecnak.",
    "target": "baktec",
    "trial_type": "dat",
    "prompt": "<p>Ez egy baktec. Elneveztem a kutyámat baktecnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">baktec<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ec",
    "s0": "Ez egy szkatyec.",
    "name": "s1",
    "value": "Azok ott szkatyecok.",
    "target": "szkatyec",
    "trial_type": "dat",
    "prompt": "<p>Ez egy szkatyec. Azok ott szkatyecok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">szkatyec<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ec",
    "s0": "Ez egy szkatyec.",
    "name": "s2",
    "value": "Elneveztem a kutyámat szkatyecnak.",
    "target": "szkatyec",
    "trial_type": "dat",
    "prompt": "<p>Ez egy szkatyec. Elneveztem a kutyámat szkatyecnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">szkatyec<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ec",
    "s0": "Ez egy pratec.",
    "name": "s1",
    "value": "Azok ott pratecok.",
    "target": "pratec",
    "trial_type": "dat",
    "prompt": "<p>Ez egy pratec. Azok ott pratecok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">pratec<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ec",
    "s0": "Ez egy pratec.",
    "name": "s2",
    "value": "Elneveztem a kutyámat pratecnak.",
    "target": "pratec",
    "trial_type": "dat",
    "prompt": "<p>Ez egy pratec. Elneveztem a kutyámat pratecnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">pratec<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ec",
    "s0": "Ez egy sapec.",
    "name": "s1",
    "value": "Azok ott sapecok.",
    "target": "sapec",
    "trial_type": "dat",
    "prompt": "<p>Ez egy sapec. Azok ott sapecok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">sapec<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ec",
    "s0": "Ez egy sapec.",
    "name": "s2",
    "value": "Elneveztem a kutyámat sapecnak.",
    "target": "sapec",
    "trial_type": "dat",
    "prompt": "<p>Ez egy sapec. Elneveztem a kutyámat sapecnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">sapec<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ec",
    "s0": "Ez egy moplec.",
    "name": "s1",
    "value": "Azok ott moplecok.",
    "target": "moplec",
    "trial_type": "dat",
    "prompt": "<p>Ez egy moplec. Azok ott moplecok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">moplec<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "ec",
    "s0": "Ez egy moplec.",
    "name": "s2",
    "value": "Elneveztem a kutyámat moplecnak.",
    "target": "moplec",
    "trial_type": "dat",
    "prompt": "<p>Ez egy moplec. Elneveztem a kutyámat moplecnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">moplec<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "el",
    "s0": "Ez egy forrel.",
    "name": "s1",
    "value": "Azok ott forrelok.",
    "target": "forrel",
    "trial_type": "dat",
    "prompt": "<p>Ez egy forrel. Azok ott forrelok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">forrel<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "el",
    "s0": "Ez egy forrel.",
    "name": "s2",
    "value": "Elneveztem a kutyámat forrelnak.",
    "target": "forrel",
    "trial_type": "dat",
    "prompt": "<p>Ez egy forrel. Elneveztem a kutyámat forrelnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">forrel<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "el",
    "s0": "Ez egy sudel.",
    "name": "s1",
    "value": "Azok ott sudelok.",
    "target": "sudel",
    "trial_type": "dat",
    "prompt": "<p>Ez egy sudel. Azok ott sudelok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">sudel<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "el",
    "s0": "Ez egy sudel.",
    "name": "s2",
    "value": "Elneveztem a kutyámat sudelnak.",
    "target": "sudel",
    "trial_type": "dat",
    "prompt": "<p>Ez egy sudel. Elneveztem a kutyámat sudelnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">sudel<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "el",
    "s0": "Ez egy kranel.",
    "name": "s1",
    "value": "Azok ott kranelok.",
    "target": "kranel",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kranel. Azok ott kranelok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kranel<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "el",
    "s0": "Ez egy kranel.",
    "name": "s2",
    "value": "Elneveztem a kutyámat kranelnak.",
    "target": "kranel",
    "trial_type": "dat",
    "prompt": "<p>Ez egy kranel. Elneveztem a kutyámat kranelnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">kranel<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "el",
    "s0": "Ez egy hacel.",
    "name": "s1",
    "value": "Azok ott hacelok.",
    "target": "hacel",
    "trial_type": "dat",
    "prompt": "<p>Ez egy hacel. Azok ott hacelok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">hacel<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "el",
    "s0": "Ez egy hacel.",
    "name": "s2",
    "value": "Elneveztem a kutyámat hacelnak.",
    "target": "hacel",
    "trial_type": "dat",
    "prompt": "<p>Ez egy hacel. Elneveztem a kutyámat hacelnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">hacel<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "el",
    "s0": "Ez egy hodel.",
    "name": "s1",
    "value": "Azok ott hodelok.",
    "target": "hodel",
    "trial_type": "dat",
    "prompt": "<p>Ez egy hodel. Azok ott hodelok.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">hodel<\/p>",
    "choices": ["f", "j"]
  },
  {
    "class": "bizalmas",
    "ending": "el",
    "s0": "Ez egy hodel.",
    "name": "s2",
    "value": "Elneveztem a kutyámat hodelnak.",
    "target": "hodel",
    "trial_type": "dat",
    "prompt": "<p>Ez egy hodel. Elneveztem a kutyámat hodelnak.<\/p><p><span style=\"font-size:24px; color:red;\">nem: \"f\"<\/span>&emsp;<span style=\"font-size:24px; color:green;\">igen: \"j\"<\/span><\/p>",
    "stimulus": "<p style=\"font-size:48px;\">hodel<\/p>",
    "choices": ["f", "j"]
  }
]
